### ISSUE TITLE
Webhook Trigger with dynamic parameters doesn't work

### ISSUE THREAD

**Issue by pkonowrocki** [weng5e/flow-connector-trigger#1]
Hi, 
I've encountered problem with Webhook Trigger With Dynamic Parameters.
When I'm trying to save Flow it prompts me with error message 
` The response from API 'test-2ddynamic-5f1682ac231a8d2257-5f26430bdda5351998' operation 'GetWebhookResponseSchema' with status code '200' does not contain a valid OpenAPI schema object.`

I'm using copy-pasted connector definition from this repo (https://github.com/weng5e/flow-connector-trigger/blob/master/connector-definition/5eDynamicParameter.swagger.json).
My api (also straight from this repo) is hosted under https://radiant-everglades-34403.herokuapp.com/index.html

**Comment by char2** [comment]
Hi - were you able to get this working?

**Comment by thahseen21** [comment]
Is this working ? I couldn't populate any properties in the dynamic content
